name: 'Custom Approval Management'
description: 'Setup approval process for teams and members'
author: 'creotiv'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'at-sign'
  color: 'green'

# Define your inputs here.
inputs:
  token:
    description: "Github token"
    required: true
  config:
    description: "Path to the action config"
    required: false
    default: '.github/custom_approval.yml'

runs:
  using: node20
  main: dist/index.js
